name: pigar
on: push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pigar dependency
        run: python -m pip install pigar
      - name: run pigar
        run: python -m pigar generate --auto-select --question-answer=yes
      - run: ls -a && cat requirements.txt
      - run: cd /home/runner/work/pigar-test/pigar-test && cat requirements.txt
      - name: compare files
        id: check
        run: "cmp requirements.txt /home/runner/work/pigar-test/pigar-test/requirements.txt \necho \"outcome=$?\" >> $GITHUB_OUTPUT\n"
      - name: check output
        run: echo "${{ steps.check.outputs.outcome }}"
      - name: add requirements.txt
        if: steps.check.outputs.outcome != 0
        run: "git config --local user.email \"github-actions@github.com\"\ngit config --local user.name \"github-actions\"\ngit add /home/runner/work/pigar-test/pigar-test/requirements.txt\ngit commit -a -m \"Add requirements.txt\"\ngit push \n"
