name: pigar
on: push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # change python version here (or select multiple)
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - run: cp requirements.txt requirements_old.txt
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pigar dependency
        run: python -m pip install pigar
      - name: run pigar
        run: python -m pigar generate --auto-select --question-answer=yes
      - name: compare files
        id: check
        # check if the old file and the new file are the same
        run: cmp --silent requirements_old.txt requirements.txt || echo "outcome=true" >> $GITHUB_OUTPUT
      - name: add requirements.txt
        # if the files are the same, then push the new requirements.txt file to the repository
        if: steps.check.outputs.outcome == 'true'
        run: "git config --local user.email \"github-actions@github.com\"\ngit config --local user.name \"github-actions\"\ngit add requirements.txt\ngit commit -a -m \"Add requirements.txt\"\ngit push \n"
